AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
  Api:
    OpenApiVersion: 3.0.2

Parameters:
  BucketNameParameter:
    Type: String
    Description: "Name of the S3 bucket to use"
    Default: "dev-example-data"

  LambdaRoleArnParameter:
    Type: String
    Description: "ARN of the IAM role to be assumed by Lambda function"
    Default: "arn:aws:iam::503561445046:role/DevExampleDataRole"

Resources:
  MyLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: example-data-layer
      Description: example project common logic layer
      Content:
        S3Bucket: sam-resources-develop
        S3Key: python_layer.zip
      CompatibleRuntimes:
        - python3.12
      LicenseInfo: Hashimoto Shingo

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: example-api
      StageName: dev
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
      Tags:
        Project: example

  MySendS3LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example-send-to-s3-function
      Handler: app.lambda_handler
      Runtime: python3.12
      Layers:
        - !Ref MyLayer
      CodeUri: send_s3/
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketNameParameter
      Role: !Ref LambdaRoleArnParameter
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /data
            Method: post
      Tags:
        Project: example

  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: auth-function
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: authorizer/
      Environment:
        Variables:
          AUDIENCE: "https://hcyckvmwm2.execute-api.ap-northeast-1.amazonaws.com/"
          AUTH0_DOMAIN: "dev-qy5ghbza7kzwxpuc.us.auth0.com"
          CLIENT_ID: "DdF1AsvUMniFWk0ys8hkTL75w1JTeEBn"
          CLIENT_SECRET: "dnPO8bGUtebCZ_-OOeK8QrCKh2EsIut5OxVB9-UBve5_3kFkpaAg0Ct_4ynbKWCF"
      Role: !Ref LambdaRoleArnParameter
      Tags:
        Project: example

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Lambda Function"
    Value: !GetAtt MySendS3LambdaFunction.Arn
